def remove_artists(all_artists):
    all_artists.remove('BestMusic')
    all_artists.remove('expirat')
    all_artists.remove('Quantic')
    all_artists.remove('DJ SET')
    all_artists.remove('LA')
    all_artists.remove('A')
    all_artists.remove('W')
    all_artists.remove('stand-up comedy')
    all_artists.remove('nedelcu')
    all_artists.remove('Teodora')
    all_artists.remove("Alex")
    all_artists.remove('Nicolae')
    all_artists.remove("Romania")
    all_artists.remove('Roberto')
    all_artists.remove('Band')
    all_artists.remove('Taylor')
    all_artists.remove('Tom')
    all_artists.remove('Isac')
    all_artists.remove('FIVE')
    all_artists.remove('Death')
    all_artists.remove('stand up')
    all_artists.remove('Raul')
    all_artists.remove('Radu')
    all_artists.remove('Valter')
    all_artists.remove('Boro')
    all_artists.remove('Cristi')

    return all_artists